In [3]:
import pandas as pd
data = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
test


station_id  Aluminium_2019  Aluminium_2020  Ammonium_2019  Ammonium_2020  \
0           163             5.0             5.0           0.08           0.08   
1           167             NaN             NaN           0.08           0.08   
2           171             NaN             NaN            NaN            NaN   
3           174             5.0             5.0           0.05           0.09   
4           178             NaN             NaN           0.05            NaN   
..          ...             ...             ...            ...            ...   
184        1941             NaN             NaN           0.05           0.05   
185        2087             5.0             NaN            NaN            NaN   
186        2206            27.2            31.1           0.05           0.05   
187        2303             NaN             5.0            NaN           0.05   
188        2307             NaN             NaN           0.53            NaN   

     Boron_2019  Boron_2020  Chloride_2019  Chloride_2020  \
0         0.071       0.062          130.0          102.0   
1           NaN         NaN            NaN            NaN   
2           NaN         NaN          112.0           90.0   
3         0.072       0.075          248.0          243.0   
4           NaN         NaN            NaN            NaN   
..          ...         ...            ...            ...   
184         NaN         NaN            NaN            NaN   
185       0.855         NaN          417.0            NaN   
186       0.018       0.013           41.0           35.0   
187         NaN       0.147            NaN           40.0   
188         NaN         NaN            NaN            NaN   

     Coli-like-bacteria-Colilert_2019  ...  Taste-ball-units_2019  \
0                                 NaN  ...                    NaN   
1                                 NaN  ...                    NaN   
2                                 NaN  ...                    NaN   
3                                 0.0  ...                    NaN   
4                                 NaN  ...                    NaN   
..                                ...  ...                    ...   
184                               NaN  ...                    NaN   
185                               0.0  ...                    NaN   
186                               1.0  ...                    NaN   
187                               0.0  ...                    NaN   
188                               0.0  ...                    NaN   

     Taste-ball-units_2020  Taste-dilution-degree_2019  \
0                      NaN                         1.0   
1                      NaN                         1.0   
2                      NaN                         2.0   
3                      NaN                         2.0   
4                      NaN                         1.0   
..                     ...                         ...   
184                    NaN                         NaN   
185                    NaN                         NaN   
186                    NaN                         2.0   
187                    NaN                         NaN   
188                    NaN                         2.0   

     Taste-dilution-degree_2020  Turbidity-NTU_2019  Turbidity-NTU_2020  \
0                           1.0                1.18                1.90   
1                           3.0                3.90                1.54   
2                           1.0                1.40                1.50   
3                           8.0                1.00                1.00   
4                           1.0                1.00                1.00   
..                          ...                 ...                 ...   
184                         2.0                4.80                1.00   
185                         2.0                1.10                1.00   
186                         2.0                1.00                1.00   
187                    

In [31]:
print(data.shape)
print()
for column in data.columns:
    print(column + "     Nan count: " + str(data[column].isna().sum()))



(440, 58)

station_id     Nan count: 0
Aluminium_2019     Nan count: 337
Aluminium_2020     Nan count: 346
Ammonium_2019     Nan count: 133
Ammonium_2020     Nan count: 150
Boron_2019     Nan count: 324
Boron_2020     Nan count: 332
Chloride_2019     Nan count: 329
Chloride_2020     Nan count: 326
Coli-like-bacteria-Colilert_2019     Nan count: 315
Coli-like-bacteria-Colilert_2020     Nan count: 315
Coli-like-bacteria_2019     Nan count: 118
Coli-like-bacteria_2020     Nan count: 120
Colony-count-at-22-C_2019     Nan count: 70
Colony-count-at-22-C_2020     Nan count: 53
Color-Pt-Co-unit_2019     Nan count: 381
Color-Pt-Co-unit_2020     Nan count: 377
Color-Pt/Co-scale_2019     Nan count: 68
Color-Pt/Co-scale_2020     Nan count: 61
Electrical-conductivity_2019     Nan count: 10
Electrical-conductivity_2020     Nan count: 4
Enterococci_2019     Nan count: 256
Enterococci_2020     Nan count: 267
Escherichia-coli-Colilert_2019     Nan count: 316
Escherichia-coli-Colilert_2020     Nan count

In [46]:
#separate 2019 and 2020 data
df2019 = data.loc[:, data.columns.str.contains('station|2019')]
df2020 = data.loc[:, data.columns.str.contains('station|2020')]
df2020

station_id  Aluminium_2020  Ammonium_2020  Boron_2020  Chloride_2020  \
0           487             NaN           0.05         NaN            NaN   
1          1555             NaN           0.05         NaN            NaN   
2           205            10.0           0.24       0.100            NaN   
3          1228             NaN           0.05       0.932            NaN   
4           470             NaN           0.05         NaN            NaN   
..          ...             ...            ...         ...            ...   
435         830             NaN            NaN         NaN            NaN   
436         803             NaN            NaN         NaN            NaN   
437        1081             5.0           0.27       0.274           14.0   
438         458             NaN           0.05         NaN            NaN   
439         725             NaN           0.05         NaN            NaN   

     Coli-like-bacteria-Colilert_2020  Coli-like-bacteria_2020  \
0                                 NaN                      0.0   
1                                 NaN                      0.0   
2                                 NaN                      0.0   
3                                 NaN                      0.0   
4                                 NaN                      2.0   
..                                ...                      ...   
435                               0.0                      NaN   
436                               NaN                      0.0   
437                               0.0                      NaN   
438                               NaN                      0.0   
439                               NaN                      0.0   

     Colony-count-at-22-C_2020  Color-Pt-Co-unit_2020  Color-Pt/Co-scale_2020  \
0                          NaN                    1.9                     NaN   
1                          0.0                    NaN                     0.0   
2                          0.0                    NaN                     0.0   
3                          2.0                    NaN                     4.0   
4                         31.0                    5.0                     NaN   
..                         ...                    ...                     ...   
435                        3.0                    NaN                     3.0   
436                       10.0                    NaN                     5.0   
437                       66.0                    NaN                     6.0   
438                        1.0                    2.7                     NaN   
439                       18.0                    NaN                     3.0   

     ...  Odour-dilution-level_2020  Oxidability_2020  Smell-ball-units_2020  \
0    ...                        NaN               NaN                    0.0   
1    ...                        1.0               NaN                    NaN   
2    ...                        1.0               NaN                    NaN   
3    ...                        NaN               NaN                    1.0   
4    ...                        NaN               NaN                    0.0   
..   ...                        ...               ...                    ...   
435  ...                        2.0               NaN                    NaN   
436  ...                        1.0               NaN                    NaN   
437  ...                        4.0              3.10                    NaN   
438  ...                        NaN               NaN                    0.0   
439  ...                        NaN              2.64                    1.0   

     Sodium_2020  Sulphate_2020  Taste-ball-units_2020  \
0            NaN            NaN                    0.0   
1            NaN            NaN                    NaN   
2            NaN            NaN                    NaN   
3            NaN            NaN                    1.0   
4            NaN            NaN                    0.0   
..   

In [77]:
#normalize the data (min-max normalization)
normalized_df2019=(df2019-df2019.min())/(df2019.max()-df2019.min())
normalized_df2019.drop(columns=['station_id'], inplace = True)

In [86]:
#try to predict with every column separately

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

def ModelForEachCol(data):
    features = data.iloc[:,-1]
    data = data.drop(columns=data.columns[-1:])
    
    for col in data.columns:
        pair = pd.concat([data[col], features], axis=1)
        pair.dropna(inplace=True)
        
        X_train, X_test, y_train, y_test = train_test_split(pair.iloc[:,0].values.reshape(-1,1), pair.iloc[:,1], train_size = 0.60, random_state = 1)
        
        rf = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=0).fit(X_train, y_train)
        
        y_pred = rf.predict(X_test)
        confusion_matrix_result = confusion_matrix(y_test.values, y_pred, labels=[1,0])  # Label=[1,0], otherwise predicted and actual axes are swapped
        print("Confusion matrix:\n%s" % confusion_matrix_result)
            
ModelForEachCol(normalized_df2019)

Confusion matrix:
[[ 0 13]
 [ 2 27]]
Confusion matrix:
[[ 3 20]
 [ 1 99]]
Confusion matrix:
[[ 1  9]
 [ 3 34]]
Confusion matrix:
[[ 2  8]
 [ 1 34]]
Confusion matrix:
[[ 6  9]
 [ 0 35]]
Confusion matrix:
[[  4  19]
 [  0 106]]
Confusion matrix:
[[  7  23]
 [  6 112]]
Confusion matrix:
[[ 0  3]
 [ 3 18]]
Confusion matrix:
[[  2  35]
 [  1 111]]
Confusion matrix:
[[  3  35]
 [  5 129]]
Confusion matrix:
[[ 1 25]
 [ 0 48]]
Confusion matrix:
[[ 0 11]
 [ 0 39]]
Confusion matrix:
[[  1  22]
 [  0 106]]
Confusion matrix:
[[ 2  9]
 [ 4 40]]
Confusion matrix:
[[ 17  16]
 [  3 113]]
Confusion matrix:
[[13 12]
 [ 2 75]]
Confusion matrix:
[[ 5  4]
 [ 6 29]]
Confusion matrix:
[[ 0  7]
 [ 3 37]]
Confusion matrix:
[[  5  20]
 [  4 105]]
Confusion matrix:
[[ 0 13]
 [ 0 44]]
Confusion matrix:
[[ 0  6]
 [ 0 32]]
Confusion matrix:
[[ 2 12]
 [ 0 44]]
Confusion matrix:
[[ 0 13]
 [ 3 46]]
Confusion matrix:
[[ 0  4]
 [ 0 34]]
Confusion matrix:
[[ 3 20]
 [ 0 99]]
Confusion matrix:
[[  5  23]
 [  4 136]]
Confus